name: Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages & accept licenses
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # Tell Gradle where the SDK is (some builds need local.properties)
      - name: Configure local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      # Use a pinned Gradle and create wrapper so we can run ./gradlew
      - name: Install Gradle 8.7 and create wrapper
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip
          export PATH="$PWD/gradle-8.7/bin:$PATH"
          gradle -v
          gradle wrapper --gradle-version 8.7

      - name: Build debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
